# -*- coding: utf-8 -*-
"""Spam_Email_Classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19M2j-ws0-YZVHJCvxo8nyItbUgb7_LVW

Import Libraries
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

"""Upload Extracted Dataset File"""

from google.colab import files
uploaded = files.upload()

"""Check Uploaded File Name"""

import os
print(os.listdir())

"""Load Dataset"""

data = pd.read_csv("spambase.data", header=None)

print(data.head())

"""Check Dataset Shape"""

print(data.shape)

"""Separate Features + Target"""

X = data.iloc[:, :-1]
y = data.iloc[:, -1]

print(X.shape)
print(y.shape)

"""Split Train/Test"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""Standardize Data"""

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""Train KNN"""

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

"""KNN Result"""

print("KNN Accuracy:", accuracy_score(y_test, knn_pred))
print(confusion_matrix(y_test, knn_pred))
print(classification_report(y_test, knn_pred))

"""Train Naïve Bayes"""

nb = GaussianNB()

nb.fit(X_train, y_train)

nb_pred = nb.predict(X_test)

"""Naïve Bayes Result"""

print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))
print(confusion_matrix(y_test, nb_pred))
print(classification_report(y_test, nb_pred))

"""Compare Both Results Clearly"""

print("KNN Accuracy:", accuracy_score(y_test, knn_pred))
print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))

"""Better Result Table"""

results = pd.DataFrame({
    'Model': ['KNN', 'Naive Bayes'],
    'Accuracy': [
        accuracy_score(y_test, knn_pred),
        accuracy_score(y_test, nb_pred)
    ]
})

print(results)

"""Confusion Matrix Visualization"""

import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, knn_pred)

plt.imshow(cm)
plt.title("KNN Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.colorbar()
plt.show()

cm = confusion_matrix(y_test, nb_pred)

plt.imshow(cm)
plt.title("Naive Bayes Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.colorbar()
plt.show()

for k in range(1,11):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print("K =", k, "Accuracy =", accuracy_score(y_test, pred))